"""Aggregate repositories — one per aggregate root.

A repository loads a root (plus its declared child collections) as a unit,
applies row-level `scope` predicates to the *root*, and tracks every root it
touches in `.seen` so the UnitOfWork can drain domain events at commit.

There is no repository for child entities: children are reached through the root.
"""
import base64
import binascii
import json
from datetime import date, datetime
from typing import Any, Optional

from sqlalchemy import inspect as sa_inspect, select, tuple_
from sqlalchemy.orm import Session, selectinload

from cosmic.domain import Context
from cosmic.errors import InvalidCursor, NotFound

DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 200


def _encode_cursor(sort_value: Any, pk_value: Any) -> str:
    if isinstance(sort_value, (datetime, date)):
        sort_value = sort_value.isoformat()
    payload = json.dumps([sort_value, str(pk_value)], separators=(",", ":"))
    return base64.urlsafe_b64encode(payload.encode()).decode().rstrip("=")


def _decode_cursor(cursor: str, sort_python_type: type) -> tuple[Any, str]:
    try:
        padded = cursor + "=" * (-len(cursor) % 4)
        sort_value, pk_value = json.loads(base64.urlsafe_b64decode(padded))
    except (ValueError, TypeError, binascii.Error) as exc:
        raise InvalidCursor(f"malformed cursor: {cursor!r}") from exc

    # Re-hydrate the sort value so it binds as the column's real type; SQLite
    # compares a TEXT-bound datetime differently from a DATETIME-bound one.
    try:
        if sort_python_type is datetime and isinstance(sort_value, str):
            sort_value = datetime.fromisoformat(sort_value)
        elif sort_python_type is date and isinstance(sort_value, str):
            sort_value = date.fromisoformat(sort_value)
    except ValueError as exc:
        raise InvalidCursor("cursor sort value does not match the column type") from exc

    return sort_value, pk_value


class AggregateRepository:
    """Repository for a single aggregate root.

    Subclass it and declare:
      ``Db``      — the root model
      ``load``    — child relationship attrs to eager-load with the root
      ``scope()`` — row-level predicates on the root, read off ``self.context``
      ``sort``    — ``(column, descending)`` ordering for `list()`; PK by default

    A plain subclass rather than something generated by a factory: `scope()` *is*
    the row-level authorization rule, so it should sit where both a reader and a
    type checker can see it.
    """

    Db: type                        # the aggregate root model
    load: tuple = ()                # child relationship attribute names to eager-load
    list_load: Optional[tuple] = None  # eager-load for `list()` only; defaults to `load`
    sort: Optional[tuple] = None    # (column, descending)
    id_field: Optional[str] = None  # identity column; defaults to the PK

    def __init__(self, session: Session, context: Optional[Context] = None):
        self.session = session
        self.context = context if context is not None else Context()
        # Keyed by id() because aggregate roots are MappedAsDataclass (unhashable).
        self.seen: dict = {}
        self._scoped = True
        self._unscoped_view: Optional["AggregateRepository"] = None

    def scope(self) -> list:
        """Row-level predicates applied to the root. Override to restrict."""
        return []

    def unscoped(self) -> "AggregateRepository":
        """A view of this aggregate with `scope()` switched off.

        Some operations genuinely need rows the principal does not own — an
        existence check on someone else's record, a background job running with
        no principal at all. Those have to be *spelled* at the call site. An
        unscoped repository sitting on the UnitOfWork under its own innocuous
        name (``uow.all_events``) is one typo away from serving another user's
        data, and nothing about `uow.events` vs `uow.all_events` says which of
        them skips authorization.

        Shares this repository's `seen`, so roots reached through the view still
        have their domain events collected at commit.
        """
        if self._unscoped_view is None:
            view = type(self)(self.session, self.context)
            view._scoped = False
            view.seen = self.seen
            view._unscoped_view = view  # unscoped().unscoped() is itself
            self._unscoped_view = view
        return self._unscoped_view

    def _pk(self):
        if self.id_field:
            return getattr(self.Db, self.id_field)
        inspected = sa_inspect(self.Db)
        assert inspected is not None  # a mapped class always inspects to a Mapper
        pk_name = inspected.mapper.primary_key[0].key
        return getattr(self.Db, pk_name)

    def _sort(self) -> tuple:
        """The ``(column, descending)`` pair `list()` orders and paginates by."""
        if self.sort is not None:
            return self.sort
        return (self._pk(), False)

    def _base_select(self, *, for_list: bool = False):
        """A scoped select of the root with its child collections eager-loaded.

        Shared by `get`, `list`, and `find_one` so a root can never be visible to
        one of them and hidden from another — row-level scope always applies to
        all three alike. Eager-loading can still differ: `list()` usually feeds a
        lightweight summary schema that needs none of the children a `get()`
        detail view does, so pass `for_list=True` to load `list_load` instead of
        `load` (both eager-load the same relationships by default).
        """
        stmt = select(self.Db)
        load = self.list_load if for_list and self.list_load is not None else self.load
        for rel in load:
            stmt = stmt.options(selectinload(getattr(self.Db, rel)))
        if self._scoped:
            for predicate in self.scope():
                stmt = stmt.where(predicate)
        return stmt

    def track(self, root):
        """Record a root so its domain events are collected at commit.

        `add`/`get`/`list`/`find_one` do this already; it is public for the rare
        query that has to be hand-written. Without it that aggregate's events are
        dropped silently, and reaching into `seen` from outside means every such
        query has to know it is a dict keyed by `id()`.
        """
        self.seen[id(root)] = root
        return root

    def add(self, root) -> None:
        self.session.add(root)  # no flush — PKs are app-assigned (uuid7)
        self.track(root)

    def remove(self, root) -> None:
        self.session.delete(root)
        self.track(root)

    def get(self, pk) -> Any:
        stmt = self._base_select().where(self._pk() == pk)
        root = self.session.scalars(stmt).unique().one_or_none()
        if root is None:
            raise NotFound(f"{self.Db.__name__.lower()} not found")
        return self.track(root)

    def find_one(self, **equals) -> Optional[Any]:
        """The first root where every ``column == value`` holds, or None.

        Deliberately keyword equality rather than arbitrary SQLAlchemy
        predicates: this is the shape an in-memory fake can implement too, so
        hand-written lookups stay covered by the repository contract tests
        instead of each one growing its own bespoke, untested method.
        """
        stmt = self._base_select().where(
            *[getattr(self.Db, name) == value for name, value in equals.items()]
        )
        root = self.session.scalars(stmt).unique().first()
        return self.track(root) if root is not None else None

    def _paginate(
        self, stmt, *, limit: int = DEFAULT_PAGE_SIZE, cursor: Optional[str] = None
    ) -> tuple[list, Optional[str]]:
        """Keyset ("seek") pagination of `stmt` over ``(sort_column, pk)``.

        The PK breaks ties so the ordering is total and a page boundary can
        neither duplicate nor skip a row, which OFFSET cannot guarantee under
        concurrent writes. Returns ``(roots, next_cursor)``; `next_cursor` is
        None on the last page. `stmt` is whatever `list()` (or an override)
        built — this only adds ordering, the cursor's keyset predicate, and
        the limit.

        Defined ahead of `list()` in this class body on purpose: once a
        method is named `list`, that name shadows the builtin for every
        annotation evaluated afterwards in the same class body, so a `list`
        return-type annotation below it would resolve to the method, not
        `builtins.list`.
        """
        limit = max(1, min(limit, MAX_PAGE_SIZE))
        sort_col, descending = self._sort()
        pk_col = self._pk()

        if descending:
            stmt = stmt.order_by(sort_col.desc(), pk_col.desc())
        else:
            stmt = stmt.order_by(sort_col.asc(), pk_col.asc())

        if cursor:
            last_sort, last_pk = _decode_cursor(cursor, self._sort_python_type(sort_col))
            keyset = tuple_(sort_col, pk_col)
            anchor = tuple_(last_sort, last_pk)
            stmt = stmt.where(keyset < anchor if descending else keyset > anchor)

        # Over-fetch by one to detect a further page without a second COUNT query.
        rows = list(self.session.scalars(stmt.limit(limit + 1)).unique().all())
        has_more = len(rows) > limit
        rows = rows[:limit]

        for root in rows:
            self.track(root)

        next_cursor = None
        if has_more and rows:
            last = rows[-1]
            next_cursor = _encode_cursor(
                getattr(last, sort_col.key), getattr(last, pk_col.key)
            )
        return rows, next_cursor

    def list(
        self, *, limit: int = DEFAULT_PAGE_SIZE, cursor: Optional[str] = None
    ) -> tuple[list, Optional[str]]:
        """Return one scoped page of roots plus the cursor for the next page.

        No filters at this level — a subclass that needs them overrides `list()`
        with its own named, typed keyword parameters, builds its filtered
        statement, and hands it to `_paginate()`. That keeps every filter a
        real, checkable parameter instead of a name matched at runtime.
        """
        return self._paginate(self._base_select(for_list=True), limit=limit, cursor=cursor)

    @staticmethod
    def _sort_python_type(sort_col) -> type:
        try:
            return sort_col.type.python_type
        except NotImplementedError:  # custom types that declare no python_type
            return str
